FROM openjdk:17.0.1-jdk-slim

EXPOSE 8080

COPY ./build/libs/*.jar app.jar

ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_URL
ARG DB_NAME

ARG CLOUDFLARE_ZONE
ARG CLOUDFLARE_AUTH_KEY

ENV DB_USERNAME ${DB_USERNAME}
ENV DB_PASSWORD ${DB_PASSWORD}
ENV DB_URL ${DB_URL}
ENV DB_NAME ${DB_NAME}

ENV CLOUDFLARE_ZONE ${CLOUDFLARE_ZONE}
ENV CLOUDFLARE_AUTH_KEY ${CLOUDFLARE_AUTH_KEY}

ENTRYPOINT ["java","-jar","/app.jar"]
